// Kubb: committed OpenAPI spec -> typed SDK + react-query hooks in src/gen
// (gitignored; regenerated by `bun run kubb` / bin/gen). Adapted from madi's
// two-spec config down to the single public spec.

import { defineConfig } from "@kubb/core";
import { pluginOas } from "@kubb/plugin-oas";
import { pluginReactQuery } from "@kubb/plugin-react-query";
import { pluginTs } from "@kubb/plugin-ts";

export default defineConfig({
  input: {
    path: "../server/spec/openapi.json",
  },
  output: {
    path: "./src/gen",
  },
  plugins: [
    pluginOas(),
    pluginTs(),
    pluginReactQuery({
      client: {
        // Spec paths are unprefixed (servers carries /api) — the baseURL
        // reassembles the real URLs, proxied to the api service in dev.
        baseURL: "/api",
        importPath: "src/api/client",
      },
    }),
  ],
});
