// Word list for word-mode random aliases (SimpleLogin ships a 2048-word EFF
// list; this is a deliberately small starter list — swap in a bigger one
// later without touching callers). All words are lowercase ASCII, unambiguous
// and inoffensive, 3-8 chars.

import { randomInt } from "node:crypto";

export const WORDS: readonly string[] = [
  "acorn",
  "amber",
  "anchor",
  "apple",
  "arrow",
  "aspen",
  "atlas",
  "autumn",
  "badge",
  "bamboo",
  "basil",
  "beacon",
  "berry",
  "birch",
  "bison",
  "blossom",
  "breeze",
  "brook",
  "butter",
  "cabin",
  "candle",
  "canyon",
  "carbon",
  "cedar",
  "cello",
  "chalk",
  "cherry",
  "cinder",
  "citrus",
  "clover",
  "cobalt",
  "comet",
  "copper",
  "coral",
  "cotton",
  "cricket",
  "crystal",
  "cypress",
  "daisy",
  "dawn",
  "delta",
  "denim",
  "drift",
  "eagle",
  "ember",
  "falcon",
  "fern",
  "fiddle",
  "flint",
  "forest",
  "fossil",
  "fox",
  "garnet",
  "geyser",
  "ginger",
  "glacier",
  "granite",
  "grove",
  "harbor",
  "hazel",
  "heron",
  "hickory",
  "honey",
  "horizon",
  "indigo",
  "iris",
  "island",
  "ivory",
  "jade",
  "jasper",
  "juniper",
  "kettle",
  "lagoon",
  "lantern",
  "laurel",
  "lavender",
  "lemon",
  "lilac",
  "linen",
  "lotus",
  "lunar",
  "maple",
  "marble",
  "meadow",
  "melon",
  "mesa",
  "mint",
  "mocha",
  "monsoon",
  "moss",
  "nectar",
  "nickel",
  "north",
  "nutmeg",
  "oasis",
  "ocean",
  "olive",
  "onyx",
  "opal",
  "orchid",
  "osprey",
  "otter",
  "panda",
  "pebble",
  "pecan",
  "penguin",
  "pepper",
  "petal",
  "pine",
  "plum",
  "pond",
  "poppy",
  "prairie",
  "quartz",
  "quill",
  "raven",
  "reef",
  "ridge",
  "river",
  "robin",
  "rustic",
  "saffron",
  "sage",
  "salmon",
  "sandal",
  "sapphire",
  "sierra",
  "silver",
  "sonnet",
  "sparrow",
  "spruce",
  "summit",
  "sunset",
  "tango",
  "teal",
  "thistle",
  "timber",
  "topaz",
  "trout",
  "tulip",
  "tundra",
  "turnip",
  "umber",
  "valley",
  "velvet",
  "violet",
  "walnut",
  "willow",
  "winter",
  "wren",
  "zephyr",
];

/**
 * SimpleLogin `random_words(words, numbers)`: `words` random words joined by
 * "_", then `numbers` random digits appended.
 */
export function randomWords(words = 2, numbers = 0): string {
  const parts: string[] = [];
  for (let i = 0; i < words; i++) parts.push(WORDS[randomInt(WORDS.length)]!);
  let out = parts.join("_");
  for (let i = 0; i < numbers; i++) out += String(randomInt(10));
  return out;
}
